version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./www:/var/www/
    ports:
      - "9999:80"
    container_name: nginx_film
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./www:/var/www/
    container_name: php_film
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
  db:
    image: mysql:8.0
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_film
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5678:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db_film